name: Java CI with JUnit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Build with Ant
        run: |
          ant -noinput -buildfile "Source Code Inspection/build.xml"

      - name: Install Apache Ant
        run: |
          sudo apt-get update
          sudo apt-get install ant

      - name: Run JUnit Tests
        run: |
          ant -f "Source Code Inspection/build.xml" test

