name: Selenium Test workflow

on: push

jobs:
  Selenium_Test_Jobs:
    name: Selenium Test Jobs
    runs-on: ubuntu-latest

    steps:
      - run: echo "test rodando no server" 
      - name: Check out source code
        uses: actions/checkout@v2.4.0
      - run: echo "This repo is ${{ github.repository }}.."
      - name: Run a inline script
        run: |
          mkdir newfolder
          ls -l
        shell: bash
      

  

